### ISSUE TITLE
FLの実装

### ISSUE THREAD

**Issue by shuto410** [posl/jProphet#23]
Project Builderを使って対象プロジェクトをビルドした後，jacocoによりテストのカバレッジ計測，およびバグ限局の疑惑値計算
バグ限局の計算に関してはochiai?やjacard?など
kgenprogを参考にするか論文をあたる

**Comment by kyamatek** [comment]
[https://github.com/kusumotolab/kGenProg/commit/320ef50ac6d3234358b3d0f0f0f21eb389c512f2](url)
kGenprogの過去のコミットを参考に,テストメソッドごとのカバレッジをとりたい
